 = Tree hoper
A little **bug** was walking trough the forest when __suddenly__ +
he saw something very very bad.
He didn't know what to do so **he** decided to ...

Since he didn't know what to do, he just wrote lines. After all, that was the point, to write 
lines to complete the task we'd given him. No wacky stories or heroic characters, just lines 
in a file that may never be read, forgotten in the meanders of GitHub.

<<<<<<< HEAD
But a **guy** wanted to read what the _bug_ wrote. He decided to bring it to the **magician** of the village.
It was a really hard work for _the magician_, he tried a lot of things but couldn't read it.
Then, he said "**SUDOOOOOOO**" and it worked.  
=======
As the creative bug he is he decied to do something about just being a part of
  a file that's never to be read. He thought to himself how could I be more 
useful bug. all of a sudden like in a flash he was flooded with ideas as how
to be more...
like >>>>>>> 6f985fb21529887f516754eab76e2b7c77dc9a23 
